### PR TITLE
Update gen_range examples (0.8)

### PR DESCRIPTION
**Pull request by jbrudant**
Previous version did not work on the playground which seems to use the latest version of rand.

### CODE REVIEW

**Review by dhardy — COMMENTED** [review]
Thanks!

Can you update with this version instead just to make the range syntax clearer?
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a3a3298b6a72b58f8957252e144be1f5

**Comment by jbrudant** [comment]
Was it on purpose that you removed the snippet about distributions ?

```rust
// Sometimes it's useful to use distributions directly:
let distr = rand::distributions::Uniform::new_inclusive(1, 100);
let mut nums = [0i32; 3];
for x in &mut nums {
    *x = rng.sample(distr);
}
```

I thought it was not and I put it back in the playground.

**Comment by dhardy** [comment]
No, it wasn't; not sure how that happened. Your version is still missing the "print nums" line (check "files changed" tab) which is probably worth having.

**Comment by jbrudant** [comment]
Sorry about that. Should be fixed now.

**Review by dhardy — APPROVED** [review]
Perfect!

**Pull request merged**
